# Dependabot configuration for Mediqux Medical Record System
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Backend Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "dmjoh"
    assignees:
      - "dmjoh"
    commit-message:
      prefix: "deps(backend)"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
      - "security"
    # Group security updates separately for immediate attention
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      production-dependencies:
        applies-to: version-updates
        patterns:
          - "express"
          - "pg"
          - "cors"
          - "bcrypt"
          - "jsonwebtoken"
          - "multer"
          - "pdf-parse"
          - "dotenv"
      dev-dependencies:
        applies-to: version-updates
        patterns:
          - "nodemon"
        update-types:
          - "minor"
          - "patch"

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "monthly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 2
    reviewers:
      - "dmjoh"
    assignees:
      - "dmjoh"
    commit-message:
      prefix: "deps(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "infrastructure"

  # Frontend Docker images
  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "monthly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 2
    reviewers:
      - "dmjoh"
    assignees:
      - "dmjoh"
    commit-message:
      prefix: "deps(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "frontend"


  # GitHub Actions (if you add any workflows)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 2
    reviewers:
      - "dmjoh"
    assignees:
      - "dmjoh"
    commit-message:
      prefix: "deps(actions)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci/cd"