#!/bin/sh

# Frontend Docker entrypoint script
# Injects environment variables into JavaScript at runtime

# Set default API URL if not provided
API_URL=${MEDIQUX_API_URL:-"http://localhost:3000/api"}

echo "Configuring frontend with API URL: $API_URL"

# Create runtime configuration file
cat > /usr/share/nginx/html/js/runtime-config.js << EOF
// Runtime configuration - generated by Docker entrypoint
window.MEDIQUX_API_URL = '$API_URL';
console.log('Mediqux runtime configuration loaded - API URL:', '$API_URL');
EOF

# Update all HTML files to include runtime-config.js before config.js
for html_file in /usr/share/nginx/html/*.html; do
    if [ -f "$html_file" ]; then
        # Add runtime-config.js before config.js if not already present
        if ! grep -q "runtime-config.js" "$html_file"; then
            sed -i 's|<script src="js/config.js"></script>|<script src="js/runtime-config.js"></script>\n    <script src="js/config.js"></script>|g' "$html_file"
        fi
    fi
done

echo "Frontend configuration complete"

# Start nginx
exec nginx -g 'daemon off;'