# =============================================================================
# Mediqux - Docker Compose for Pre-built Containers  
# =============================================================================
# This version uses pre-built images with environment variables from .env file
# =============================================================================

services:
  # PostgreSQL Database
  postgres:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - mediqux_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API server (pre-built image)
  backend:
    image: your-registry/mediqux-backend:latest  # Replace with your image
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DEBUG=${DEBUG}
      - LOG_LEVEL=${LOG_LEVEL}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE}
      - UPLOAD_PATH=${UPLOAD_PATH}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mediqux_network

  # Frontend web server (pre-built image)
  frontend:
    image: your-registry/mediqux-frontend:latest  # Replace with your image
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - MEDIQUX_API_URL=${MEDIQUX_API_URL}
    networks:
      - mediqux_network

volumes:
  postgres_data:
    driver: local

networks:
  mediqux_network:
    driver: bridge