services:
  postgres:
    image: postgres:17-alpine
    container_name: mediqux_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mediqux_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: mediqux_backend
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DEBUG: ${DEBUG:-true}
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      DB_HOST: postgres
      DB_PORT: ${POSTGRES_PORT:-5432}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      FRONTEND_URL: http://${FRONTEND_HOST:-localhost}:${FRONTEND_PORT:-8080}
      JWT_SECRET: ${JWT_SECRET}
      MAX_FILE_SIZE: ${MAX_FILE_SIZE:-10MB}
      UPLOAD_PATH: ${UPLOAD_PATH:-/app/uploads}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mediqux_network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mediqux_frontend
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    environment:
      MEDIQUX_API_URL: http://${BACKEND_HOST:-localhost}:${BACKEND_PORT:-3000}/api
    volumes:
      - ./frontend/css:/usr/share/nginx/html/css
      - ./frontend/js:/usr/share/nginx/html/js
    depends_on:
      - backend
    networks:
      - mediqux_network

volumes:
  postgres_data:
    driver: local

networks:
  mediqux_network:
    name: mediqux_network
    driver: bridge