sonar.projectKey=DMJoh_Mediqux_3373e484-62a4-4bd7-8193-d049544ebdf6
sonar.projectName=Mediqux


sonar.sources=backend/src,frontend/js
sonar.exclusions=**/node_modules/**,**/package-lock.json,backend/seeders/**,backend/migrations/**

sonar.sourceEncoding=UTF-8
