// Runtime configuration - generated by Docker entrypoint
window.MEDIQUX_API_URL = 'http://localhost:3000/api';
console.log('Mediqux runtime configuration loaded - API URL:', 'http://localhost:3000/api');
